version: '3.8'
services:
  dashboard:
    build:
      context: .
    container_name: productionpal_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./productionpal_dashboard.log:/app/productionpal_dashboard.log
    command: streamlit run app/dashboard.py --server.port=8501 --server.address=0.0.0.0

  sensor_mocker:
    build:
      context: .
    container_name: productionpal_sensor
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./productionpal_sensor.log:/app/productionpal_sensor.log
    command: python sensor_mocker.py
