version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./productionpal_dashboard.log:/app/productionpal_dashboard.log
    depends_on:
      - sensor_mocker

  sensor_mocker:
    build: .
    command: ["python", "sensor_mocker.py"]
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./productionpal_sensor.log:/app/productionpal_sensor.log
